name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn test:typecheck

      - name: Build package
        run: cd packages/excalidraw && yarn build:esm

      - name: Publish to GitHub Packages
        run: cd packages/excalidraw && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
